// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: comm/comm.proto

package go_comm_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RequestTest) Reset() {
	*x = RequestTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTest) ProtoMessage() {}

func (x *RequestTest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTest.ProtoReflect.Descriptor instead.
func (*RequestTest) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{0}
}

func (x *RequestTest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type ResponseTest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ResponseTest) Reset() {
	*x = ResponseTest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseTest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTest) ProtoMessage() {}

func (x *ResponseTest) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTest.ProtoReflect.Descriptor instead.
func (*ResponseTest) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{1}
}

func (x *ResponseTest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RequestUnirse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body int32 `protobuf:"varint,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RequestUnirse) Reset() {
	*x = RequestUnirse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestUnirse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestUnirse) ProtoMessage() {}

func (x *RequestUnirse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestUnirse.ProtoReflect.Descriptor instead.
func (*RequestUnirse) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{2}
}

func (x *RequestUnirse) GetBody() int32 {
	if x != nil {
		return x.Body
	}
	return 0
}

type RequestEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body int32 `protobuf:"varint,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RequestEtapa) Reset() {
	*x = RequestEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEtapa) ProtoMessage() {}

func (x *RequestEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEtapa.ProtoReflect.Descriptor instead.
func (*RequestEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{3}
}

func (x *RequestEtapa) GetBody() int32 {
	if x != nil {
		return x.Body
	}
	return 0
}

type RequestRonda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body int32 `protobuf:"varint,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *RequestRonda) Reset() {
	*x = RequestRonda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRonda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRonda) ProtoMessage() {}

func (x *RequestRonda) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRonda.ProtoReflect.Descriptor instead.
func (*RequestRonda) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{4}
}

func (x *RequestRonda) GetBody() int32 {
	if x != nil {
		return x.Body
	}
	return 0
}

type RequestPrimeraEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada  int32 `protobuf:"varint,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
	Ronda   int32 `protobuf:"varint,2,opt,name=ronda,proto3" json:"ronda,omitempty"`
	Jugador int32 `protobuf:"varint,3,opt,name=jugador,proto3" json:"jugador,omitempty"`
}

func (x *RequestPrimeraEtapa) Reset() {
	*x = RequestPrimeraEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPrimeraEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPrimeraEtapa) ProtoMessage() {}

func (x *RequestPrimeraEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPrimeraEtapa.ProtoReflect.Descriptor instead.
func (*RequestPrimeraEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{5}
}

func (x *RequestPrimeraEtapa) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *RequestPrimeraEtapa) GetRonda() int32 {
	if x != nil {
		return x.Ronda
	}
	return 0
}

func (x *RequestPrimeraEtapa) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

type RequestSegundaEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada  int32 `protobuf:"varint,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
	Jugador int32 `protobuf:"varint,2,opt,name=jugador,proto3" json:"jugador,omitempty"`
}

func (x *RequestSegundaEtapa) Reset() {
	*x = RequestSegundaEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestSegundaEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestSegundaEtapa) ProtoMessage() {}

func (x *RequestSegundaEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestSegundaEtapa.ProtoReflect.Descriptor instead.
func (*RequestSegundaEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{6}
}

func (x *RequestSegundaEtapa) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *RequestSegundaEtapa) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

type RequestTerceraEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Jugada  int32 `protobuf:"varint,1,opt,name=jugada,proto3" json:"jugada,omitempty"`
	Jugador int32 `protobuf:"varint,2,opt,name=jugador,proto3" json:"jugador,omitempty"`
}

func (x *RequestTerceraEtapa) Reset() {
	*x = RequestTerceraEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestTerceraEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestTerceraEtapa) ProtoMessage() {}

func (x *RequestTerceraEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestTerceraEtapa.ProtoReflect.Descriptor instead.
func (*RequestTerceraEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{7}
}

func (x *RequestTerceraEtapa) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

func (x *RequestTerceraEtapa) GetJugador() int32 {
	if x != nil {
		return x.Jugador
	}
	return 0
}

type ResponseUnirse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NumeroJugador int32 `protobuf:"varint,1,opt,name=numeroJugador,proto3" json:"numeroJugador,omitempty"`
}

func (x *ResponseUnirse) Reset() {
	*x = ResponseUnirse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseUnirse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseUnirse) ProtoMessage() {}

func (x *ResponseUnirse) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseUnirse.ProtoReflect.Descriptor instead.
func (*ResponseUnirse) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseUnirse) GetNumeroJugador() int32 {
	if x != nil {
		return x.NumeroJugador
	}
	return 0
}

type ResponseEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body         int32 `protobuf:"varint,1,opt,name=body,proto3" json:"body,omitempty"`
	TerminoJuego bool  `protobuf:"varint,2,opt,name=terminoJuego,proto3" json:"terminoJuego,omitempty"`
}

func (x *ResponseEtapa) Reset() {
	*x = ResponseEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEtapa) ProtoMessage() {}

func (x *ResponseEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEtapa.ProtoReflect.Descriptor instead.
func (*ResponseEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{9}
}

func (x *ResponseEtapa) GetBody() int32 {
	if x != nil {
		return x.Body
	}
	return 0
}

func (x *ResponseEtapa) GetTerminoJuego() bool {
	if x != nil {
		return x.TerminoJuego
	}
	return false
}

type ReponseRonda struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body         int32 `protobuf:"varint,1,opt,name=body,proto3" json:"body,omitempty"`
	TerminoJuego bool  `protobuf:"varint,2,opt,name=terminoJuego,proto3" json:"terminoJuego,omitempty"`
}

func (x *ReponseRonda) Reset() {
	*x = ReponseRonda{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReponseRonda) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReponseRonda) ProtoMessage() {}

func (x *ReponseRonda) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReponseRonda.ProtoReflect.Descriptor instead.
func (*ReponseRonda) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{10}
}

func (x *ReponseRonda) GetBody() int32 {
	if x != nil {
		return x.Body
	}
	return 0
}

func (x *ReponseRonda) GetTerminoJuego() bool {
	if x != nil {
		return x.TerminoJuego
	}
	return false
}

type ResponsePrimeraEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado  bool `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
	Ganador bool `protobuf:"varint,2,opt,name=ganador,proto3" json:"ganador,omitempty"`
}

func (x *ResponsePrimeraEtapa) Reset() {
	*x = ResponsePrimeraEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePrimeraEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePrimeraEtapa) ProtoMessage() {}

func (x *ResponsePrimeraEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePrimeraEtapa.ProtoReflect.Descriptor instead.
func (*ResponsePrimeraEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{11}
}

func (x *ResponsePrimeraEtapa) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

func (x *ResponsePrimeraEtapa) GetGanador() bool {
	if x != nil {
		return x.Ganador
	}
	return false
}

type ResponseSegundaEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado bool `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *ResponseSegundaEtapa) Reset() {
	*x = ResponseSegundaEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseSegundaEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseSegundaEtapa) ProtoMessage() {}

func (x *ResponseSegundaEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseSegundaEtapa.ProtoReflect.Descriptor instead.
func (*ResponseSegundaEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{12}
}

func (x *ResponseSegundaEtapa) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

type ResponseTerceraEtapa struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Estado bool `protobuf:"varint,1,opt,name=estado,proto3" json:"estado,omitempty"`
}

func (x *ResponseTerceraEtapa) Reset() {
	*x = ResponseTerceraEtapa{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseTerceraEtapa) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseTerceraEtapa) ProtoMessage() {}

func (x *ResponseTerceraEtapa) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseTerceraEtapa.ProtoReflect.Descriptor instead.
func (*ResponseTerceraEtapa) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{13}
}

func (x *ResponseTerceraEtapa) GetEstado() bool {
	if x != nil {
		return x.Estado
	}
	return false
}

type RequestRJDN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NJugador int32 `protobuf:"varint,1,opt,name=n_jugador,json=nJugador,proto3" json:"n_jugador,omitempty"`
	NRonda   int32 `protobuf:"varint,2,opt,name=n_ronda,json=nRonda,proto3" json:"n_ronda,omitempty"`
	Jugada   int32 `protobuf:"varint,3,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *RequestRJDN) Reset() {
	*x = RequestRJDN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRJDN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRJDN) ProtoMessage() {}

func (x *RequestRJDN) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRJDN.ProtoReflect.Descriptor instead.
func (*RequestRJDN) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{14}
}

func (x *RequestRJDN) GetNJugador() int32 {
	if x != nil {
		return x.NJugador
	}
	return 0
}

func (x *RequestRJDN) GetNRonda() int32 {
	if x != nil {
		return x.NRonda
	}
	return 0
}

func (x *RequestRJDN) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

type ResponseRJDN struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ResponseRJDN) Reset() {
	*x = ResponseRJDN{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRJDN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRJDN) ProtoMessage() {}

func (x *ResponseRJDN) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRJDN.ProtoReflect.Descriptor instead.
func (*ResponseRJDN) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{15}
}

func (x *ResponseRJDN) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RequestRJJ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NJugador int32 `protobuf:"varint,1,opt,name=n_jugador,json=nJugador,proto3" json:"n_jugador,omitempty"`
	NRonda   int32 `protobuf:"varint,2,opt,name=n_ronda,json=nRonda,proto3" json:"n_ronda,omitempty"`
	Jugada   int32 `protobuf:"varint,3,opt,name=jugada,proto3" json:"jugada,omitempty"`
}

func (x *RequestRJJ) Reset() {
	*x = RequestRJJ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestRJJ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRJJ) ProtoMessage() {}

func (x *RequestRJJ) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRJJ.ProtoReflect.Descriptor instead.
func (*RequestRJJ) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{16}
}

func (x *RequestRJJ) GetNJugador() int32 {
	if x != nil {
		return x.NJugador
	}
	return 0
}

func (x *RequestRJJ) GetNRonda() int32 {
	if x != nil {
		return x.NRonda
	}
	return 0
}

func (x *RequestRJJ) GetJugada() int32 {
	if x != nil {
		return x.Jugada
	}
	return 0
}

type ResponseRJJ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Body string `protobuf:"bytes,1,opt,name=body,proto3" json:"body,omitempty"`
}

func (x *ResponseRJJ) Reset() {
	*x = ResponseRJJ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_comm_comm_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseRJJ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseRJJ) ProtoMessage() {}

func (x *ResponseRJJ) ProtoReflect() protoreflect.Message {
	mi := &file_comm_comm_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseRJJ.ProtoReflect.Descriptor instead.
func (*ResponseRJJ) Descriptor() ([]byte, []int) {
	return file_comm_comm_proto_rawDescGZIP(), []int{17}
}

func (x *ResponseRJJ) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

var File_comm_comm_proto protoreflect.FileDescriptor

var file_comm_comm_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x63, 0x6f, 0x6d, 0x6d, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x04, 0x63, 0x6f, 0x6d, 0x6d, 0x22, 0x21, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f,
	0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x23,
	0x0a, 0x0d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74,
	0x61, 0x70, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x22, 0x0a, 0x0c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x22, 0x5d, 0x0a, 0x13, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x72, 0x61, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f,
	0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x72, 0x6f, 0x6e, 0x64, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x13, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x67, 0x75, 0x6e, 0x64, 0x61, 0x45, 0x74, 0x61, 0x70,
	0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x13, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x65,
	0x72, 0x63, 0x65, 0x72, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75,
	0x67, 0x61, 0x64, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x12, 0x18, 0x0a, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x22, 0x36, 0x0a, 0x0e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x12, 0x24,
	0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x6f, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x65, 0x72,
	0x6d, 0x69, 0x6e, 0x6f, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x0c, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x6f, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x46, 0x0a,
	0x0c, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x12, 0x0a,
	0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x62, 0x6f, 0x64,
	0x79, 0x12, 0x22, 0x0a, 0x0c, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x6f, 0x4a, 0x75, 0x65, 0x67,
	0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x74, 0x65, 0x72, 0x6d, 0x69, 0x6e, 0x6f,
	0x4a, 0x75, 0x65, 0x67, 0x6f, 0x22, 0x48, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x72, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x16, 0x0a,
	0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65,
	0x73, 0x74, 0x61, 0x64, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x67, 0x61, 0x6e, 0x61, 0x64, 0x6f, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x67, 0x61, 0x6e, 0x61, 0x64, 0x6f, 0x72, 0x22,
	0x2e, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x53, 0x65, 0x67, 0x75, 0x6e,
	0x64, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x2e, 0x0a, 0x14, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x65, 0x72, 0x63, 0x65,
	0x72, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x65, 0x73, 0x74, 0x61, 0x64, 0x6f, 0x22,
	0x5b, 0x0a, 0x0b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x4a, 0x44, 0x4e, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x5f, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x5f, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x52,
	0x6f, 0x6e, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22, 0x22, 0x0a, 0x0c,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x4a, 0x44, 0x4e, 0x12, 0x12, 0x0a, 0x04,
	0x62, 0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79,
	0x22, 0x5a, 0x0a, 0x0a, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x4a, 0x4a, 0x12, 0x1b,
	0x0a, 0x09, 0x6e, 0x5f, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x6e, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x5f, 0x72, 0x6f, 0x6e, 0x64, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x52,
	0x6f, 0x6e, 0x64, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x22, 0x21, 0x0a, 0x0b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x4a, 0x4a, 0x12, 0x12, 0x0a, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x32,
	0xdc, 0x04, 0x0a, 0x04, 0x43, 0x6f, 0x6d, 0x6d, 0x12, 0x32, 0x0a, 0x07, 0x46, 0x75, 0x6e, 0x54,
	0x65, 0x73, 0x74, 0x12, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x65, 0x73, 0x74, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x65, 0x73, 0x74, 0x22, 0x00, 0x12, 0x41, 0x0a, 0x12,
	0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x4a, 0x75, 0x65, 0x67, 0x6f, 0x43, 0x61, 0x6c, 0x61, 0x6d,
	0x61, 0x72, 0x12, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x1a, 0x14, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x55, 0x6e, 0x69, 0x72, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x38, 0x0a, 0x0b, 0x49, 0x6e, 0x69, 0x63, 0x69, 0x6f, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x12,
	0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x1a, 0x13, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x00, 0x12, 0x37, 0x0a, 0x0b, 0x49, 0x6e, 0x69,
	0x63, 0x69, 0x6f, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x12, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x6f, 0x6e, 0x64, 0x61, 0x1a, 0x12, 0x2e, 0x63,
	0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x6f, 0x6e, 0x64, 0x61,
	0x22, 0x00, 0x12, 0x4d, 0x0a, 0x12, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x50, 0x72, 0x69, 0x6d,
	0x65, 0x72, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x72, 0x61, 0x45, 0x74,
	0x61, 0x70, 0x61, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x50, 0x72, 0x69, 0x6d, 0x65, 0x72, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22,
	0x00, 0x12, 0x4d, 0x0a, 0x12, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x53, 0x65, 0x67, 0x75, 0x6e,
	0x64, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x65, 0x67, 0x75, 0x6e, 0x64, 0x61, 0x45, 0x74, 0x61,
	0x70, 0x61, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x53, 0x65, 0x67, 0x75, 0x6e, 0x64, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x00,
	0x12, 0x4d, 0x0a, 0x12, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x61, 0x54, 0x65, 0x72, 0x63, 0x65, 0x72,
	0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x12, 0x19, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x54, 0x65, 0x72, 0x63, 0x65, 0x72, 0x61, 0x45, 0x74, 0x61, 0x70,
	0x61, 0x1a, 0x1a, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x54, 0x65, 0x72, 0x63, 0x65, 0x72, 0x61, 0x45, 0x74, 0x61, 0x70, 0x61, 0x22, 0x00, 0x12,
	0x3f, 0x0a, 0x16, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67, 0x61,
	0x64, 0x61, 0x4a, 0x75, 0x67, 0x61, 0x64, 0x6f, 0x72, 0x12, 0x10, 0x2e, 0x63, 0x6f, 0x6d, 0x6d,
	0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x4a, 0x4a, 0x1a, 0x11, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x4a, 0x4a, 0x22, 0x00,
	0x12, 0x3c, 0x0a, 0x11, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x72, 0x4a, 0x75, 0x67,
	0x61, 0x64, 0x61, 0x44, 0x4e, 0x12, 0x11, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x52, 0x4a, 0x44, 0x4e, 0x1a, 0x12, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x2e,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x4a, 0x44, 0x4e, 0x22, 0x00, 0x42, 0x27,
	0x5a, 0x25, 0x65, 0x78, 0x61, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f,
	0x2d, 0x63, 0x6f, 0x6d, 0x6d, 0x2d, 0x67, 0x72, 0x70, 0x63, 0x3b, 0x67, 0x6f, 0x5f, 0x63, 0x6f,
	0x6d, 0x6d, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_comm_comm_proto_rawDescOnce sync.Once
	file_comm_comm_proto_rawDescData = file_comm_comm_proto_rawDesc
)

func file_comm_comm_proto_rawDescGZIP() []byte {
	file_comm_comm_proto_rawDescOnce.Do(func() {
		file_comm_comm_proto_rawDescData = protoimpl.X.CompressGZIP(file_comm_comm_proto_rawDescData)
	})
	return file_comm_comm_proto_rawDescData
}

var file_comm_comm_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_comm_comm_proto_goTypes = []interface{}{
	(*RequestTest)(nil),          // 0: comm.RequestTest
	(*ResponseTest)(nil),         // 1: comm.ResponseTest
	(*RequestUnirse)(nil),        // 2: comm.RequestUnirse
	(*RequestEtapa)(nil),         // 3: comm.RequestEtapa
	(*RequestRonda)(nil),         // 4: comm.RequestRonda
	(*RequestPrimeraEtapa)(nil),  // 5: comm.RequestPrimeraEtapa
	(*RequestSegundaEtapa)(nil),  // 6: comm.RequestSegundaEtapa
	(*RequestTerceraEtapa)(nil),  // 7: comm.RequestTerceraEtapa
	(*ResponseUnirse)(nil),       // 8: comm.ResponseUnirse
	(*ResponseEtapa)(nil),        // 9: comm.ResponseEtapa
	(*ReponseRonda)(nil),         // 10: comm.ReponseRonda
	(*ResponsePrimeraEtapa)(nil), // 11: comm.ResponsePrimeraEtapa
	(*ResponseSegundaEtapa)(nil), // 12: comm.ResponseSegundaEtapa
	(*ResponseTerceraEtapa)(nil), // 13: comm.ResponseTerceraEtapa
	(*RequestRJDN)(nil),          // 14: comm.RequestRJDN
	(*ResponseRJDN)(nil),         // 15: comm.ResponseRJDN
	(*RequestRJJ)(nil),           // 16: comm.RequestRJJ
	(*ResponseRJJ)(nil),          // 17: comm.ResponseRJJ
}
var file_comm_comm_proto_depIdxs = []int32{
	0,  // 0: comm.Comm.FunTest:input_type -> comm.RequestTest
	2,  // 1: comm.Comm.UnirseJuegoCalamar:input_type -> comm.RequestUnirse
	3,  // 2: comm.Comm.InicioEtapa:input_type -> comm.RequestEtapa
	4,  // 3: comm.Comm.InicioRonda:input_type -> comm.RequestRonda
	5,  // 4: comm.Comm.JugadaPrimeraEtapa:input_type -> comm.RequestPrimeraEtapa
	6,  // 5: comm.Comm.JugadaSegundaEtapa:input_type -> comm.RequestSegundaEtapa
	7,  // 6: comm.Comm.JugadaTerceraEtapa:input_type -> comm.RequestTerceraEtapa
	16, // 7: comm.Comm.RegistrarJugadaJugador:input_type -> comm.RequestRJJ
	14, // 8: comm.Comm.RegistrarJugadaDN:input_type -> comm.RequestRJDN
	1,  // 9: comm.Comm.FunTest:output_type -> comm.ResponseTest
	8,  // 10: comm.Comm.UnirseJuegoCalamar:output_type -> comm.ResponseUnirse
	9,  // 11: comm.Comm.InicioEtapa:output_type -> comm.ResponseEtapa
	10, // 12: comm.Comm.InicioRonda:output_type -> comm.ReponseRonda
	11, // 13: comm.Comm.JugadaPrimeraEtapa:output_type -> comm.ResponsePrimeraEtapa
	12, // 14: comm.Comm.JugadaSegundaEtapa:output_type -> comm.ResponseSegundaEtapa
	13, // 15: comm.Comm.JugadaTerceraEtapa:output_type -> comm.ResponseTerceraEtapa
	17, // 16: comm.Comm.RegistrarJugadaJugador:output_type -> comm.ResponseRJJ
	15, // 17: comm.Comm.RegistrarJugadaDN:output_type -> comm.ResponseRJDN
	9,  // [9:18] is the sub-list for method output_type
	0,  // [0:9] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_comm_comm_proto_init() }
func file_comm_comm_proto_init() {
	if File_comm_comm_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_comm_comm_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseTest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestUnirse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRonda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPrimeraEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestSegundaEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestTerceraEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseUnirse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReponseRonda); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePrimeraEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseSegundaEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseTerceraEtapa); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRJDN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRJDN); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestRJJ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_comm_comm_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseRJJ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_comm_comm_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_comm_comm_proto_goTypes,
		DependencyIndexes: file_comm_comm_proto_depIdxs,
		MessageInfos:      file_comm_comm_proto_msgTypes,
	}.Build()
	File_comm_comm_proto = out.File
	file_comm_comm_proto_rawDesc = nil
	file_comm_comm_proto_goTypes = nil
	file_comm_comm_proto_depIdxs = nil
}
